# Generated by Django 6.0 on 2025-12-15 06:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id_log', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=45)),
                ('headers', models.JSONField()),
                ('request_body', models.JSONField()),
                ('request_time', models.DateTimeField()),
                ('status_code', models.IntegerField()),
                ('response_time', models.DateTimeField()),
                ('response_body', models.JSONField()),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'log',
            },
        ),
    ]
