# Generated by Django 6.0 on 2026-02-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='user_create',
            field=models.CharField(db_index=True, default='SYSTEM', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_update',
            field=models.CharField(db_index=True, default='SYSTEM', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='user_create',
            field=models.CharField(db_index=True, default='SYSTEM', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='user_update',
            field=models.CharField(db_index=True, default='SYSTEM', max_length=50),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='user_usernam_b79065_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_create'], name='user_user_cr_589fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_update'], name='user_user_up_c26ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['id_user_role'], name='user_role_id_user_be0c49_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['name'], name='user_role_name_c651be_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user_create'], name='user_role_user_cr_983d29_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user_update'], name='user_role_user_up_bc260e_idx'),
        ),
    ]
